import React, { useEffect, useRef } from "react";

export const TfIdf = (props) => {
  const { data, setData } = props;

  //レビューだけを抽出

  const documents = data.map((data) =>
    data.reviews.map((reviews) => reviews.review)
  );

  // 各ゲームごとにレビューをまとめる
  const combinedReviews = documents.map((gameReviews) => gameReviews.join(" "));

  const stopWords = [
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "you're",
    "you've",
    "you'll",
    "you'd",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "she's",
    "her",
    "hers",
    "herself",
    "it",
    "it's",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "that'll",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "don't",
    "should",
    "should've",
    "now",
    "d",
    "ll",
    "m",
    "o",
    "re",
    "ve",
    "y",
    "ain",
    "aren",
    "aren't",
    "couldn",
    "couldn't",
    "didn",
    "didn't",
    "doesn",
    "doesn't",
    "hadn",
    "hadn't",
    "hasn",
    "hasn't",
    "haven",
    "haven't",
    "isn",
    "isn't",
    "ma",
    "mightn",
    "mightn't",
    "mustn",
    "mustn't",
    "needn",
    "needn't",
    "shan",
    "shan't",
    "shouldn",
    "shouldn't",
    "wasn",
    "wasn't",
    "weren",
    "weren't",
    "won",
    "won't",
    "wouldn",
    "wouldn't",
    "a",
    "but",
    "during",
    "hows",
    "it's",
    "said",
    "this",
    "we're",
    "who've",
    "about",
    "by",
    "each",
    "however",
    "it's",
    "says",
    "those",
    "we've",
    "whove",
    "above",
    "can",
    "either",
    "i",
    "its",
    "see",
    "through",
    "we've",
    "will",
    "across",
    "can't",
    "for",
    "i'd",
    "let's",
    "she",
    "to",
    "weve",
    "with",
    "after",
    "can't",
    "from",
    "i'd",
    "let's",
    "she'd",
    "too",
    "were",
    "within",
    "all",
    "cant",
    "given",
    "i'll",
    "lets",
    "she'd",
    "towards",
    "what",
    "without",
    "along",
    "cannot",
    "had",
    "i'll",
    "may",
    "shed",
    "under",
    "what's",
    "won't",
    "also",
    "could",
    "has",
    "i'm",
    "me",
    "she'll",
    "until",
    "what's",
    "won't",
    "am",
    "couldn't",
    "have",
    "i'm",
    "more",
    "she'll",
    "us",
    "whats",
    "would",
    "an",
    "couldn't",
    "having",
    "im",
    "most",
    "shell",
    "use",
    "when",
    "wouldn't",
    "and",
    "did",
    "he",
    "i've",
    "much",
    "should",
    "used",
    "when's",
    "wouldn't",
    "any",
    "didn't",
    "he'd",
    "i've",
    "must",
    "since",
    "uses",
    "when's",
    "you",
    "are",
    "aren't",
    "didnt",
    "he'd",
    "ive",
    "my",
    "so",
    "using",
    "whens",
    "you'd",
    "aren't",
    "didnt",
    "hed",
    "if",
    "no",
    "some",
    "very",
    "where",
    "you'd",
    "aren't",
    "didnt",
    "he'll",
    "in",
    "not",
    "such",
    "want",
    "whether",
    "youd",
    "arent",
    "do",
    "he'll",
    "instead",
    "now",
    "than",
    "was",
    "which",
    "you'll",
    "as",
    "does",
    "her",
    "into",
    "of",
    "that",
    "wasn't",
    "while",
    "you'll",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "between",
    "both",
    "ME",
    "MY",
    "MYSELF",
    "WE",
    "OUR",
    "OURS",
    "OURSELVES",
    "YOU",
    "YOU'RE",
    "YOU'VE",
    "YOU'LL",
    "YOU'D",
    "YOUR",
    "YOURS",
    "YOURSELF",
    "YOURSELVES",
    "HE",
    "HIM",
    "HIS",
    "HIMSELF",
    "SHE",
    "SHE'S",
    "HER",
    "HERS",
    "HERSELF",
    "IT",
    "IT'S",
    "ITS",
    "ITSELF",
    "THEY",
    "THEM",
    "THEIR",
    "THEIRS",
    "THEMSELVES",
    "WHAT",
    "WHICH",
    "WHO",
    "WHOM",
    "THIS",
    "THAT",
    "THAT'LL",
    "THESE",
    "THOSE",
    "AM",
    "IS",
    "ARE",
    "WAS",
    "WERE",
    "BE",
    "BEEN",
    "BEING",
    "HAVE",
    "HAS",
    "HAD",
    "HAVING",
    "DO",
    "DOES",
    "DID",
    "DOING",
    "A",
    "AN",
    "THE",
    "AND",
    "BUT",
    "IF",
    "OR",
    "BECAUSE",
    "AS",
    "UNTIL",
    "WHILE",
    "OF",
    "AT",
    "BY",
    "FOR",
    "WITH",
    "ABOUT",
    "AGAINST",
    "BETWEEN",
    "INTO",
    "THROUGH",
    "DURING",
    "BEFORE",
    "AFTER",
    "ABOVE",
    "BELOW",
    "TO",
    "FROM",
    "UP",
    "DOWN",
    "IN",
    "OUT",
    "ON",
    "OFF",
    "OVER",
    "UNDER",
    "AGAIN",
    "FURTHER",
    "THEN",
    "ONCE",
    "HERE",
    "THERE",
    "WHEN",
    "WHERE",
    "WHY",
    "HOW",
    "ALL",
    "ANY",
    "BOTH",
    "EACH",
    "FEW",
    "MORE",
    "MOST",
    "OTHER",
    "SOME",
    "SUCH",
    "NO",
    "NOR",
    "NOT",
    "ONLY",
    "OWN",
    "SAME",
    "SO",
    "THAN",
    "TOO",
    "VERY",
    "S",
    "T",
    "CAN",
    "WILL",
    "JUST",
    "DON",
    "DON'T",
    "SHOULD",
    "SHOULD'VE",
    "NOW",
    "D",
    "LL",
    "M",
    "O",
    "RE",
    "VE",
    "Y",
    "AIN",
    "AREN",
    "AREN'T",
    "COULDN",
    "COULDN'T",
    "DIDN",
    "DIDN'T",
    "DOESN",
    "DOESN'T",
    "HADN",
    "HADN'T",
    "HASN",
    "HASN'T",
    "HAVEN",
    "HAVEN'T",
    "ISN",
    "ISN'T",
    "MA",
    "MIGHTN",
    "MIGHTN'T",
    "MUSTN",
    "MUSTN'T",
    "NEEDN",
    "NEEDN'T",
    "SHAN",
    "SHAN'T",
    "SHOULDN",
    "SHOULDN'T",
    "WASN",
    "WASN'T",
    "WEREN",
    "WEREN'T",
    "WON",
    "WON'T",
    "WOULDN",
    "WOULDN'T",
    "I",
    "Me",
    "My",
    "Myself",
    "We",
    "Our",
    "Ours",
    "Ourselves",
    "You",
    "You're",
    "You've",
    "You'll",
    "You'd",
    "Your",
    "Yours",
    "Yourself",
    "Yourselves",
    "He",
    "Him",
    "His",
    "Himself",
    "She",
    "She's",
    "Her",
    "Hers",
    "Herself",
    "It",
    "It's",
    "Its",
    "Itself",
    "They",
    "Them",
    "Their",
    "Theirs",
    "Themselves",
    "What",
    "Which",
    "Who",
    "Whom",
    "This",
    "That",
    "That'll",
    "These",
    "Those",
    "Am",
    "Is",
    "Are",
    "Was",
    "Were",
    "Be",
    "Been",
    "Being",
    "Have",
    "Has",
    "Had",
    "Having",
    "Do",
    "Does",
    "Did",
    "Doing",
    "A",
    "An",
    "The",
    "And",
    "But",
    "If",
    "Or",
    "Because",
    "As",
    "Until",
    "While",
    "Of",
    "At",
    "By",
    "For",
    "With",
    "About",
    "Against",
    "Between",
    "Into",
    "Through",
    "During",
    "Before",
    "After",
    "Above",
    "Below",
    "To",
    "From",
    "Up",
    "Down",
    "In",
    "Out",
    "On",
    "Off",
    "Over",
    "Under",
    "Again",
    "Further",
    "Then",
    "Once",
    "Here",
    "There",
    "When",
    "Where",
    "Why",
    "How",
    "All",
    "Any",
    "Both",
    "Each",
    "Few",
    "More",
    "Most",
    "Other",
    "Some",
    "Such",
    "No",
    "Nor",
    "Not",
    "Only",
    "Own",
    "Same",
    "So",
    "Than",
    "Too",
    "Very",
    "S",
    "T",
    "Can",
    "Will",
    "Just",
    "Don",
    "Don't",
    "Should",
    "Should've",
    "Now",
    "D",
    "Ll",
    "M",
    "O",
    "Re",
    "Ve",
    "Y",
    "Ain",
    "Aren",
    "Aren't",
    "Couldn",
    "Couldn't",
    "Didn",
    "Didn't",
    "Doesn",
    "Doesn't",
    "Hadn",
    "Hadn't",
    "Hasn",
    "Hasn't",
    "Haven",
    "Haven't",
    "Isn",
    "Isn't",
    "Ma",
    "Mightn",
    "Mightn't",
    "Mustn",
    "Mustn't",
    "Needn",
    "Needn't",
    "Shan",
    "Shan't",
    "Shouldn",
    "Shouldn't",
    "Wasn",
    "Wasn't",
    "Weren",
    "Weren't",
    "Won",
    "Won't",
    "Wouldn",
    "Wouldn't",
    "and",
    "the",
    "of",
    "your",
    "to",
    "you",
    "I",
    "The",
    "This",
    "game",
    "is",
    "it",
    "GAME",
    "Game",
    "THE",
    "IS",
    "Is",
    "best",
    "good",
    "like",
    "You",
    "And",
    "then",
    "Will",
    "Of",
    "Over",
    "how",
    "there",
    "fun",
  ];

  // 各ゲームごとに reviews の中の要素を単語ごとに分割して配列にする
  // 被っているやつを除く
  const uniqueWordsArray = documents.map((item) => {
    const uniqueWords = new Set();
    item.forEach((review) => {
      review.split(/\s+/).forEach((word) => {
        if (word.length > 1 && /^[a-zA-Z]+$/.test(word)) {
          uniqueWords.add(word);
        }
      });
    });

    return Array.from(uniqueWords);
  });

  const unique = uniqueWordsArray.map((array) =>
    array.filter((i) => {
      return !stopWords.find((item) => i === item);
    })
  );

  //除かない
  const wordsArray = documents.map((item) => {
    const allWords = [];
    item.forEach((review) => {
      review.split(/\s+/).forEach((word) => {
        allWords.push(word);
      });
    });
    return allWords;
  });

  ///////////////////////////////////////////////
  const TFIDFofGame = [];

  for (let i = 0; i < data.length; i++) {
    function calculateIDF(documents, terms) {
      const idfResults = {};

      terms.forEach((term) => {
        const documentCountWithTerm = documents.reduce(
          (count, document) => (document.includes(term) ? count + 1 : count),
          0
        );
        const idf = Math.log(documents.length / documentCountWithTerm);
        idfResults[term] = idf + 1;
      });

      return idfResults;
    }

    const terms = unique[i]; // 例としてuniqueWordsArrayの最初の文書の単語を使用

    const idfResults = calculateIDF(documents[i], terms);

    // TFを計算する関数
    function calculateTF(document) {
      const wordCount = {}; // 単語の出現回数を保持するオブジェクト

      // 文書内の各単語の出現回数を数える
      document.forEach((word) => {
        wordCount[word] = (wordCount[word] || 0) + 1;
      });

      // 各単語の出現回数を文書内の単語数で割ってTFを計算
      const tf = {};
      const totalWords = document.length;
      Object.keys(wordCount).forEach((word) => {
        tf[word] = wordCount[word] / totalWords;
      });

      return tf;
    }

    // TFを計算
    const tfResult = calculateTF(wordsArray[i]);

    // オブジェクト同士のプロパティの値を掛け算
    const resultObject = multiplyObjects(tfResult, idfResults);

    //////////////////////////////////////

    const TFIDF = [];
    for (const key in resultObject) {
      const findWord = data[i].wordcloud.find((word) => word.text === key);

      TFIDF.push({
        text: key,
        value: resultObject[key],
        rating: findWord ? findWord.rating : 0.5,
      });
    }

    TFIDFofGame.push(TFIDF);
  }

  //TF-IDF計算
  function multiplyObjects(obj1, obj2) {
    const result = {};

    // obj1とobj2のプロパティをイテレート
    for (const key in obj1) {
      const number = 3;
      if (obj1.hasOwnProperty(key) && obj2.hasOwnProperty(key)) {
        result[key] = parseFloat(
          (obj1[key] * obj2[key] * 10 ** number).toFixed(number)
        );
      }
    }

    return result;
  }

  setData(
    data.map((item, i) => {
      return { ...item, TFIDF: TFIDFofGame[i] };
    })
  );
};
